### ISSUE TITLE
Ctrl-Z

### ISSUE THREAD

**Issue by MCBailey-CTS** [dulimarta/spherical-easel#18]
Problem: There are no common keyboard shortcuts like ctlr-z for undo

Heuristic: Consistency and standards

Severity: 1

Solution: Add keyboard shortcuts

**Comment by dickinson0718** [comment]
I have added some of these shortcut as of version 87ed022. Ctrl-z and ctrl-y undo and redo the last active and with the select tool activate, ctrl-a selects all non-label objects.
