### ISSUE TITLE
tool hints:  quickly disappear

### ISSUE THREAD

**Issue by don-sp** [dulimarta/spherical-easel#2]
This issue is with the text that pops up when a tool is clicked. The text boxes appear for a second only, even though they have what looks like a delete "X," suggesting they will display until dismissed.

**Comment by don-sp** [comment]
A correction -- this issue is with the text that pops up when a tool is clicked.  The text boxes appear for a second only, even though they have what looks like a delete "X," suggesting they will display until dismissed.

**Comment by dickinson0718** [comment]
Closing as a duplicate of issue #23
