### ISSUE TITLE
Adjust Box Sphere Display

### ISSUE THREAD

**Issue by MCBailey-CTS** [dulimarta/spherical-easel#25]
Problem: The size of the box that displays the sphere isn't adjustable

Location: Sphere display

Heuristic: Consistency and standards

Severity: 1

Solution: Allow the user to adjust the size of the sphere display

**Comment by dickinson0718** [comment]
I don't understand this. If you adjust the size of browser window, the size of the sphere adjusts to fill the maximum available area while keeping the aspect ratio of one.
