### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by dickinson0718** [dulimarta/spherical-easel#48]
Steps to Reproduce:
1. Start SE
2. Click the object tree icon.  It will correctly say "No objects in database" and it will have executed the `zeroObjects()` method in `ObjectTree.vue`
3. Click back to the tools and create a line or anything plottable.
4. Click back to the object tree and notice that it still says "No objects in database" and did not execute `zeroObjects()`

Thoughts:  Is this a vue update issue?

**Comment by dulimarta** [comment]
No an issue anymore.
