### ISSUE TITLE
Limits on size of save file

### ISSUE THREAD

**Issue by dickinson0718** [dulimarta/spherical-easel#5]
I created a large file with 1 line, 20-30 points, 16 line segments and I couldn’t save it ( “Can’t save document FirebaseError: The value of property “preview” is longer than 1048487 bytes.“)

Probably some setting in Firebase or maybe we’ll have to be more efficient in creating the string we are saving. I can see how to handle that.

**Comment by dulimarta** [comment]
Fixed by uploading the script and its SVG preview to Firebase Storage
