### ISSUE TITLE
Labels cannot be moved by MoveHandler

### ISSUE THREAD

**Issue by dulimarta** [dulimarta/spherical-easel#67]
To reproduce:
1. Create a point
2. Switch to the Move Objects tool
3. Hover the mouse of the label of the point

Expected behavior:

- The label should get highlighted
- The user should be able to drag the label to different locations around the point

Trace of `git bisect`: the issue seemed to show up for the first time in commit d131760e08a52a252312f7cb2b7a4be538b1f55b (Jun 2, 2022)

**Comment by dickinson0718** [comment]
Canvas width and canvas height now used in `SELabel` on lines ~267-~288. Resolved in commit  c6aa58a972bfd8f7a967806e44b083ef18dba63e
