### ISSUE TITLE
Style Drawer: Style Issue Opening Panels

### ISSUE THREAD

**Issue by dickinson0718** [dulimarta/spherical-easel#74]
1) Create a circle, 
2) select it, 
3) open the back panel, do nothing, 
4) open the front by clicking on the icon (immediately to the right of the "Foreground Style" tool tip

 I couldn't get the front panel to open (and after that back panel won't open again). 

Here is the view after step 3 but before step 4.
<img width="943" alt="Screenshot 2024-06-14 at 11 46 51 AM" src="https://github.com/dulimarta/spherical-easel/assets/9343855/9da1f528-8efa-4937-a335-c48d3a42e0c0">

**Comment by dulimarta** [comment]
There was a runtime error in one of the wathcers in `FrontBackStyle.vue` caused by the following 
if-statement:

```
if (Object.hasOwn(opt, 'dashArray')) {
  const arr = opt.dashArray!
}
```

Fix the issue by changing the above if-statement to

```
if (Array.isArray(opt.dashArray)) {
  const arr = opt.dashArray
}
```
