### ISSUE TITLE
Style Drawer: Label Display Mode

### ISSUE THREAD

**Issue by dickinson0718** [dulimarta/spherical-easel#76]
If a circle or other non-measurable object is selected, the "Value only" and the "Name & Value" options should not appear in the "Label Display mode" (on the label sub-panel in the text tab). The only objects for which these options should appear are angle markers, polygons and points (after they have measured with the Coordinate tool) and segments (after they have been measured with the line segment length tool.

**Comment by dulimarta** [comment]
`MoveHandler` checks for `isFreeToMove()`, but `SENodule::isFreeToMove()` returns `true` when every parent of an object is a free point.

Fix the issue by overriding `SELabel::isFreeToMove()` to return `true`

**Comment by dulimarta** [comment]
Fixed by adding a new boolean state (`measurableSelections`) in the Style store
