### ISSUE TITLE
Selecting Labels 

### ISSUE THREAD

**Issue by dickinson0718** [dulimarta/spherical-easel#77]
Create a circle, display its label, turn on the move tool. We can't move the label of the circle.  

Same is true for segments, circles, and lines -- but you *can* select and move the label of a point.

**Comment by dulimarta** [comment]
`MoveHandler` checks for `isFreeToMove()`, but `SENodule::isFreeToMove()` returns `true` when every parent of an object is a free point.

Fix the issue by overriding `SELabel::isFreeToMove()` to return `true`
