### ISSUE TITLE
Extra line in angle markers

### ISSUE THREAD

**Issue by dulimarta** [dulimarta/spherical-easel#79]
Step to reproduce (use the attached Picture #1 as reference)

1. Create a segment (from P1 to P2)
2. Create a circle
3. Measure angle between the segment and the circle

At this point the angle marker is displayed correctly.

Picture 1

![Screenshot 2024-07-11 154139](https://github.com/dulimarta/spherical-easel/assets/3125417/b81e0648-a38b-477f-93e6-32f7d82db7f6)

4. Move point P1 to move the segment to a position shown in Picture 2
 
The angle marker now shows extra line

Picture 2
![angle-marker-twojs-0 8](https://github.com/dulimarta/spherical-easel/assets/3125417/b131411a-f90f-4f70-b85b-b9158c25b8e3)

**Comment by dickinson0718** [comment]
Perhaps in the future I'll add a measure angle between a segment and a circle but in this case  I think this is a measure of the angle formed by points 

1) P1
2) The intersection of the circle and the segment
3) The point on the circle
