### ISSUE TITLE
Dash pattern on lines and segment (and circle?)

### ISSUE THREAD

**Issue by dickinson0718** [dulimarta/spherical-easel#80]
When styling a line or segment (but not circle?), turning on the dash pattern array  ("Use dash pattern") yield this error on the javascript console

```
localhost/:1 Uncaught (in promise) Maximum recursive updates exceeded. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.
```

For line and segment the "Swap Dash/Gap" doesn't have any effect. (After the above error, the dash style sub-panel is available.) However is might be a side effect of the error.

For circles, I could turn on the dash pattern, but swapping the dash and gap yielded the same error as above.

**Comment by dulimarta** [comment]
This should be fixed in commit [44663f8](https://github.com/dulimarta/spherical-easel/commit/44663f8d1b5ee55f323a42d03715056556214a4d)
