### ISSUE TITLE
Beta or advanced features mode tools list issue

### ISSUE THREAD

**Issue by dickinson0718** [dulimarta/spherical-easel#86]
When you are in the beta or advanced features mode (i.e. using http://localhost:8080/?features=beta ) and you change from the `Tools` menu/side bar to the `Object`  sidebar and then back to the `Tools` menu, the only tool that is available is the "Developer Only Tool". All other tools are hidden. :-(

**Comment by dulimarta** [comment]
The fix is embarrassingly simple 😄. It was a typo: `slice(0)` vs. `splice(0)` around line 120 of `ToolGroups.vue`

```
permissibleButtonGroup = toolGroups.splice(0) // The incorrect code
```

```
permissibleButtonGroup = toolGroups.slice(0)
```
