### ISSUE TITLE
Account Setting Page Return To Constructions

### ISSUE THREAD

**Issue by dickinson0718** [dulimarta/spherical-easel#89]
Currently there is no (direct) way to go from the account settings page back to the sphere canvas.

Can we make the save button on the settings view (below) a "Save and Return" button so that there is a programatic way to return to the sphere canvas and creating new constructions?

<img width="1200" alt="Screenshot 2024-07-30 at 1 00 08 PM" src="https://github.com/user-attachments/assets/18a8d3c8-5354-4003-9db9-9a809fdbd333">

**Comment by dulimarta** [comment]
Fix in commit aa313beb
